### ISSUE TITLE
Cannot OAuth

### ISSUE THREAD

**Issue by BodhisattwaMandal** [wikisource/ia-upload#27]
OAuth is not happening, landing on a blank page after clicking on Allow button.

**Comment by samwilson** [comment]
Sorry about this! I'm fixing it now. (Not yet sure where the problem is.)

**Comment by samwilson** [comment]
Can you try it again now? It should be working.

**Comment by BodhisattwaMandal** [comment]
Yes, its working. Thanks a lot @samwilson
