### ISSUE TITLE
Stuck during ''Merging modified XML into full DjVu file''

### ISSUE THREAD

**Issue by BodhisattwaMandal** [wikisource/ia-upload#30]
Books are stuck in queue for long time in the step where modified XML is merged into full DjVu file. For example, [this](https://tools.wmflabs.org/ia-upload/log/b28035264) for 10 days and [this](https://tools.wmflabs.org/ia-upload/log/armaghclergypari00lesl) for 20 days.

**Comment by samwilson** [comment]
It's because they're too big! :-(

This is being tracked at https://phabricator.wikimedia.org/T161396 — can you add any extra ones to that ticket?

Thanks! :)
