### ISSUE TITLE
File failed to upload

### ISSUE THREAD

**Issue by Aubreymcfato** [wikisource/ia-upload#31]
I can't seem to upload this file: misteridipolizia00niceuoft.
It has the djvu directly in IA, and when I try the option "Use existing Djvu", I get `File failed to upload`.
If I try the "from original scans", it doesn't say anything, and it shows me the home page of the tool again. No feedback or error.

**Comment by samwilson** [comment]
This seems to be a known and undiagnosed problem:
https://phabricator.wikimedia.org/T159796

You can see the log of any IA Upload job by clicking the 'log' link in the job-queue table.
E.g.: https://tools.wmflabs.org/ia-upload/log/misteridipolizia00niceuoft

(I'll close this issue in favour of tracking in the Phabricator one.)

**Comment by samwilson** [comment]
Oh! No, I see the other problem: after submitting a job, the job-queue isn't displayed! I'll create a separate issue for that.
