### ISSUE TITLE
Look for duplicate files with linksearch

### ISSUE THREAD

**Issue by nemobis** [wikisource/ia-upload#6]
To avoid https://github.com/Tpt/ia-upload/issues/5 it would be useful to look for the IA URL in the linksearch API and perhaps confirm with the CommonsMetadata API. I'll send a patch at some point.

**Comment by samwilson** [comment]
And we can check Wikidata for matches between Commons files and IA identifiers too (although that's not all that widely used yet, I think).

**Comment by samwilson** [comment]
Moved to Phabricator, to keep all issues together: https://phabricator.wikimedia.org/T178262
